#!/bin/sh

set -e

case $RECRYPT_NETWORK in
  local|regtest)
    SELECT_NETWORK=-regtest
    ;;
  test|testnet)
    SELECT_NETWORK=-testnet
    ;;
  main|mainnet)
    SELECT_NETWORK=
    ;;
  *)
    echo "Unknown network: $RECRYPT_NETWORK"
    exit 1
esac

mkdir -p $RECRYPT_DATADIR

exec recryptd ${SELECT_NETWORK} \
  -rpcbind=0.0.0.0:8489 -rpcallowip=172.17.0.0/16 \
  -datadir=$RECRYPT_DATADIR \
  -logevents \
  -rpcuser=$RECRYPT_RPC_USER -rpcpassword=$RECRYPT_RPC_PASS \
  -printtoconsole
